### ISSUE TITLE
2ch FHSS 

### ISSUE THREAD

**Issue by lowdrapht** [colzilla/usb-rc#2]
Will any of the codes for the itsy bitsy work for the stx2. It's only a two channel radio. I've connected my board to the receiver with A3 and A4 connected to Thr and Str, but i'm not getting any input when i try to calibrate the controller/transmitter. I copied over the sanwa_ssr code.

**Comment by colzilla** [comment]
The sanwa code it for sanwa tx/rx in SSR mode - the STX2 doesn’t have this mode.

Please try the “regular” version :)

Thanks

//Colin

On Jul 6, 2020, at 20:49, lowdrapht <notifications@github.com> wrote:

﻿

Will any of the codes for the itsy bitsy work for the stx2. It's only a two channel radio. I've connected my board to the receiver with A3 and A4 connected to Thr and Str, but i'm not getting any input when i try to calibrate the controller/transmitter. I copied over the sanwa_ssr code.

**Comment by lowdrapht** [comment]
Gotcha, is the regular version the RC_NOR? Thanks for the reply!

**Comment by colzilla** [comment]
For a 4-ch, yes. The 2-ch version is the “code.py” file :)

//Colin

On Jul 7, 2020, at 07:40, lowdrapht <notifications@github.com> wrote:

﻿

Gotcha, is the regular version the RC_NOR? Thanks for the reply!

**Comment by lowdrapht** [comment]
That worked! Thanks so much!

**Comment by colzilla** [comment]
:) you’re welcome! Enjoy!

//Colin

On Jul 7, 2020, at 12:01, lowdrapht <notifications@github.com> wrote:

﻿

That worked! Thanks so much!
